name: Indeed Web Scrape Pipeline

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 12 * * *'  # Optional: runs daily at 12:00 UTC

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run notebook
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          jupyter nbconvert --to notebook --execute your_notebook_name.ipynb --inplace
